name: 'Build'

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
  
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Install definitions
      run: yarn
      
    - name: Build the project
      run: yarn tsc

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          dist/**
